
class SteamUtils
{
public:
  virtual void GetInstallPath(void);
  virtual void GetUserBaseFolderInstallImage(void);
  virtual void GetManagedContentRoot(void);
  virtual void GetSecondsSinceAppActive(void);
  virtual void GetSecondsSinceComputerActive(void);
  virtual void SetComputerActive(void);
  virtual void GetConnectedUniverse(void);
  virtual void GetServerRealTime(void);
  virtual void GetIPCountry(void);
  virtual void GetImageSize(int,unsigned int *,unsigned int *);
  virtual void GetImageRGBA(int,unsigned char *,int);
  virtual void GetCSERIPPort(unsigned int *,unsigned short *);
  virtual void GetNumRunningApps(void);
  virtual void GetCurrentBatteryPower(void);
  virtual void GetBatteryInformation(int *,bool *);
  virtual void SetOfflineMode(bool);
  virtual void GetOfflineMode(void);
  virtual void SetAppIDForCurrentPipe(unsigned int,bool);
  virtual void GetAppID(void);
  virtual void SetAPIDebuggingActive(bool,bool);
  virtual void AllocPendingAPICallHandle(void);
  virtual bool IsAPICallCompleted(unsigned long long,bool *);
  virtual void GetAPICallFailureReason(unsigned long long);
  virtual bool GetAPICallResult(unsigned long long,void *,int,int,bool *);
  virtual void SetAPICallResultWithoutPostingCallback(unsigned long long,void const*,int,int);
  virtual void SignalAppsToShutDown(void);
  virtual void SignalServiceAppsToDisconnect(void);
  virtual void TerminateAllAppsMultiStep(unsigned int);
  virtual void GetCellID(void);
  virtual void BIsGlobalInstance(void);
  virtual void CheckFileSignature(char const*);
  virtual void GetBuildID(void);
  virtual void SetCurrentUIMode(int);
  virtual void GetCurrentUIMode(void);
  virtual void ShutdownLauncher(bool,bool);
  virtual void SetLauncherType(int);
  virtual void GetLauncherType(void);
  virtual void ShowGamepadTextInput(int,int,char const*,unsigned int,char const*);
  virtual void GetEnteredGamepadTextLength(void);
  virtual void GetEnteredGamepadTextInput(char *,unsigned int);
  virtual void GamepadTextInputClosed(int,bool,char const*);
  virtual void SetSpew(int,int,int);
  virtual void BDownloadsDisabled(void);
  virtual void SetFocusedWindow(CGameID,bool);
  virtual void GetSteamUILanguage(void);
  virtual void CheckSteamReachable(void);
  virtual void SetLastGameLaunchMethod(EGameLaunchMethod);
  virtual void SetVideoAdapterInfo(int,int,int,int,int,int,char const*);
  virtual void SetControllerOverrideMode(CGameID,char const*,unsigned int);
  virtual void SetOverlayWindowFocusForPipe(bool,bool,CGameID);
  virtual void GetGameOverlayUIInstanceFocusGameID(bool *);
  virtual void SetControllerConfigFileForAppID(unsigned int,char const*);
  virtual void GetControllerConfigFileForAppID(unsigned int,char *,unsigned int);
  virtual void IsSteamRunningInVR(void);
  virtual void BIsRunningOnAlienwareAlpha(void);
  virtual void StartVRDashboard(void);
  virtual void IsVRHeadsetStreamingEnabled(unsigned int);
  virtual void SetVRHeadsetStreamingEnabled(unsigned int,bool);
  virtual void GenerateSupportSystemReport(void);
  virtual void GetSupportSystemReport(char *,unsigned int,unsigned char *,unsigned int);
  virtual void GetAppIdForPid(unsigned int,bool);
  virtual void SetClientUIProcess(void);
  virtual void BIsClientUIInForeground(void);
  virtual void SetOverlayChatBrowserInfo(unsigned int,int,int,int,int);
  virtual void ClearOverlayChatBrowserInfo(unsigned int);
  virtual void GetOverlayChatBrowserInfo(int *,unsigned int,unsigned int *);
  virtual void DispatchClientUINotification(int,char const*,unsigned int);
  virtual void RespondToClientUINotification(unsigned int,bool,unsigned int);
  virtual void DispatchClientUICommand(char const*,unsigned int);
  virtual void DispatchComputerActiveStateChange(void);
  virtual void DispatchOpenURLInClient(char const*,unsigned int,bool);
  virtual void UpdateWideVineCDM(char const*);
  virtual void DispatchClearAllBrowsingData(void);
  virtual void DispatchClientSettingsChanged(void);
  virtual void DispatchClientPostMessage(char const*,char const*,char const*);
  virtual void IsSteamChinaLauncher(void);
  virtual void InitFilterText(unsigned int);
  virtual void FilterText(unsigned int,char *,unsigned int,char const*,bool);
  virtual void GetIPv6ConnectivityState(int);
  virtual void RecordSteamInterfaceCreation(char const*,char const*);
  virtual void StartRuntimeInformationGathering(void);
  virtual void GetRuntimeInformation(void);
  virtual void GetCloudGamingPlatform(void);
  virtual void BGetMacAddresses(unsigned long long *,unsigned int,unsigned int *);
  virtual void BGetDiskSerialNumber(char *,int);
  virtual void TestHTTP(char const*);
};

