
class SteamUtils
{
public:
  virtual void GetInstallPath(void);
  virtual void GetUserBaseFolderInstallImage(void);
  virtual void GetManagedContentRoot(void);
  virtual void GetSecondsSinceAppActive(void);
  virtual void GetSecondsSinceComputerActive(void);
  virtual void SetComputerActive(void);
  virtual void GetConnectedUniverse(void);
  virtual void GetServerRealTime(void);
  virtual void GetIPCountry(void);
  virtual void GetImageSize(int,unsigned int *,unsigned int *);
  virtual void GetImageRGBA(int,unsigned char *,int);
  virtual void GetCSERIPPort(unsigned int *,unsigned short *);
  virtual void GetNumRunningApps(void);
  virtual void GetCurrentBatteryPower(void);
  virtual void SetOfflineMode(bool);
  virtual void GetOfflineMode(void);
  virtual void SetAppIDForCurrentPipe(unsigned int,bool);
  virtual void GetAppID(void);
  virtual void SetAPIDebuggingActive(bool,bool);
  virtual void AllocPendingAPICallHandle(void);
  virtual bool IsAPICallCompleted(unsigned long long,bool *);
  virtual void GetAPICallFailureReason(unsigned long long);
  virtual bool GetAPICallResult(unsigned long long,void *,int,int,bool *);
  virtual void SetAPICallResultWithoutPostingCallback(unsigned long long,void const*,int,int);
  virtual void SignalAppsToShutDown(void);
  virtual void SignalServiceAppsToDisconnect(void);
  virtual void TerminateAllAppsMultiStep(unsigned int);
  virtual void GetCellID(void);
  virtual void BIsGlobalInstance(void);
  virtual void CheckFileSignature(char const*);
  virtual void GetBuildID(void);
  virtual void SetCurrentUIMode(int);
  virtual void GetCurrentUIMode(void);
  virtual void ShutdownLauncher(bool,bool);
  virtual void SetLauncherType(int);
  virtual void GetLauncherType(void);
  virtual void ShowGamepadTextInput(int,int,char const*,unsigned int,char const*);
  virtual void GetEnteredGamepadTextLength(void);
  virtual void GetEnteredGamepadTextInput(char *,unsigned int);
  virtual void GamepadTextInputClosed(int,bool,char const*);
  virtual void SetSpew(int,int,int);
  virtual void BDownloadsDisabled(void);
  virtual void SetFocusedWindow(int,unsigned long long,bool);
  virtual void GetSteamUILanguage(void);
  virtual void CheckSteamReachable(void);
  virtual void SetLastGameLaunchMethod(int);
  virtual void SetVideoAdapterInfo(int,int,int,int,int,int,char const*);
  virtual void SetControllerOverrideMode(int,char const*,unsigned int);
  virtual void SetOverlayWindowFocusForPipe(bool,bool,int);
  virtual void GetGameOverlayUIInstanceFocusGameID(bool *);
  virtual void SetControllerConfigFileForAppID(unsigned int,char const*);
  virtual void GetControllerConfigFileForAppID(unsigned int,char *,unsigned int);
  virtual void IsSteamRunningInVR(void);
  virtual void BIsRunningOnAlienwareAlpha(void);
  virtual void StartVRDashboard(void);
  virtual void IsVRHeadsetStreamingEnabled(unsigned int);
  virtual void SetVRHeadsetStreamingEnabled(unsigned int,bool);
  virtual void GenerateSupportSystemReport(void);
  virtual void GetSupportSystemReport(char *,unsigned int,unsigned char *,unsigned int);
  virtual void GetAppIdForPid(unsigned int,bool);
  virtual void SetClientUIProcess(void);
  virtual void BIsClientUIInForeground(void);
  virtual void SetOverlayChatBrowserInfo(unsigned int,int);
  virtual void ClearOverlayChatBrowserInfo(unsigned int);
  virtual void GetOverlayChatBrowserInfo(void *,unsigned int,unsigned int *);
  virtual void DispatchClientUINotification(int,char const*,unsigned int);
  virtual void RespondToClientUINotification(unsigned int,bool,unsigned int);
  virtual void DispatchClientUICommand(char const*,unsigned int);
  virtual void DispatchComputerActiveStateChange(void);
  virtual void DispatchOpenURLInClient(char const*,unsigned int,bool);
};

